add_library(libClaPP_GSL INTERFACE)
if(libClaPP_SUBMODULE_DEPENDENCIES)
    if(NOT TARGET GSL)
        set(GSL_CXX_STANDARD "17" CACHE STRING "Use c++ standard")
        add_subdirectory("${THIRD_PARTY_DIR}/GSL" EXCLUDE_FROM_ALL)
    endif()
    target_link_libraries(libClaPP_GSL INTERFACE GSL)
else()
    if(TARGET GSL)
        target_link_libraries(libClaPP_GSL INTERFACE GSL)
    else()
        find_path(libClaPP_GSL_INCLUDE_DIR NAMES gsl_assert PATH_SUFFIXES gsl)
        if(NOT libClaPP_GSL_INCLUDE_DIR)
            message(FATAL_ERROR "Could not find GSL library.")
        endif()
        target_include_directories(libClaPP_GSL INTERFACE ${libClaPP_GSL_INCLUDE_DIR}/..)
    endif()
endif()

if(libClaPP_PEDANTIC_COMPILER_FLAGS)
    if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
        target_compile_options(libClaPP_GSL INTERFACE -Wno-weak-vtables)
    endif()
endif()
