if(libClaPP_BUILD_TESTS)
    if(libClaPP_SUBMODULE_DEPENDENCIES)
        if(NOT TARGET gmock_main)
            add_subdirectory("${THIRD_PARTY_DIR}/googletest" EXCLUDE_FROM_ALL)
            target_compile_features(gtest PUBLIC cxx_std_17)    #changing gtest (and its further libs gmock and gmock_main) to be C++17, otherwise we will get linker error.
            add_library(libClaPP_gmock_main INTERFACE)
            target_link_libraries(libClaPP_gmock_main INTERFACE gmock_main)
            if ("${CMAKE_CXX_COMPILER_ID}" STREQUAL "Clang")
                target_compile_options(libClaPP_gmock_main INTERFACE -Wno-used-but-marked-unused -Wno-covered-switch-default -Wno-exit-time-destructors)
            endif()
        endif()
    else()
        pkg_check_modules(GMOCK REQUIRED gmock_main>=1.10.0)
        add_library(libClaPP_gmock_main INTERFACE)
        target_include_directories(libClaPP_gmock_main SYSTEM INTERFACE ${GMOCK_INCLUDE_DIRS})
        target_link_libraries(libClaPP_gmock_main INTERFACE ${GMOCK_LIBRARIES})
    endif()
endif()
